name: Monitorear plantilla del Sevilla FC

on:
  schedule:
    - cron: "0 * * * *" # Ejecutar cada hora
  workflow_dispatch: {} # Permite ejecución manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar Playwright
        run: |
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
