name: Comprobar plantillas LaLiga

on:
  schedule:
    - cron: "*/30 * * * *" # Cada 30 minutos
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install aiohttp beautifulsoup4 python-telegram-bot==20.3

      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Guardar datos actualizados
        uses: EndBug/add-and-commit@v9
        with:
          message: "Actualización de plantillas"
          add: "plantillas.json"
