name: Monitor plantillas LaLiga

on:
  schedule:
    - cron: "*/30 * * * *" # cada 30 minutos
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Muy importante para usar el PAT

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        run: python main.py

      - name: Commit y push de cambios
        uses: EndBug/add-and-commit@v9
        with:
          message: "Actualización de plantillas"
          add: "plantillas.json"
          author_name: "Bot LaLiga"
          author_email: "bot@laliga.com"
          github_token: ${{ secrets.PAT_TOKEN }}
